// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import TodoListConcept from "./TodoList/TodoListConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import AIPrioritizedTaskConcept from "./AIPrioritizedTask/AIPrioritizedTaskConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";
import ExternalAssignmentSyncConcept from "./ExternalAssignmentSync/ExternalAssignmentSyncConcept.ts";

export type { default as TodoListConcept } from "./TodoList/TodoListConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as AIPrioritizedTaskConcept } from "./AIPrioritizedTask/AIPrioritizedTaskConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";
export type { default as ExternalAssignmentSyncConcept } from "./ExternalAssignmentSync/ExternalAssignmentSyncConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const TodoList = Engine.instrumentConcept(new TodoListConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const AIPrioritizedTask = Engine.instrumentConcept(new AIPrioritizedTaskConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
export const ExternalAssignmentSync = Engine.instrumentConcept(new ExternalAssignmentSyncConcept(db));
