import bcrypt from "bcrypt";

/**
 * Hashes a plain-text password using bcrypt.
 * @param password The plain-text password to hash.
 * @returns The hashed password string.
 */
export async function hashPassword(password: string): Promise<string> {
  // A salt value is automatically generated by hashSync().
  // The cost factor (number of rounds) is set to 10.
  const salt = bcrypt.genSaltSync(10);
  return bcrypt.hashSync(password, salt);
}

/**
 * Compares a plain-text password with a hashed password.
 * @param password The plain-text password.
 * @param hashedPassword The hashed password.
 * @returns True if the passwords match, false otherwise.
 */
export async function comparePassword(
  password: string,
  hashedPassword: string,
): Promise<boolean> {
  return bcrypt.compareSync(password, hashedPassword);
}